### ISSUE TITLE
Licensing question: art/map_items.xcf

### ISSUE THREAD

**Issue by anholt** [ValyriaTear/ValyriaTear#216]
Assuming that my pull request for licensing clarification is accurate, this is my last licensing question:

I couldn't tell what the licensing was supposed to be on this file, whether it was derived from both CC and GPL source content, or dual-licensed by both authors.  Could you clarify this?

**Comment by RyDroid** [comment]
http://mentors.debian.net/package/valyriatear redirects to https://mentors.debian.net/packages/index?packagename=None
Searching "valy" (in case insensitive mode) returns nothing. Is the work accessible somewhere?

**Comment by Bertram25** [comment]
oh nowws 😭 
@anholt I know you are very busy. Could you simply upload your work somewhere so that @RyDroid can takeover?

**Comment by RyDroid** [comment]
> why not create a Valyria-art repository if it is to become a problem.

- I believe that it is a licensing problem that can not be resolved by simply separating files in 2 debian source packages, but I may be wrong.
- Having a separate repo for art will imply more work : 2 source packages instead of one (that generates 2 "real" packages), but it would simplify the copyright file by splitting it.
