### ISSUE TITLE
Enemy skill callouts too long

### ISSUE THREAD

**Issue by Suitecake** [ValyriaTear/ValyriaTear#470]
Enemy skill callouts are somewhat too long for the enemy attack animation and delay. In fights of many enemies (such as some of the fights in the east room of Elbrus Shrine, with five snakes), it's difficult to tell when a skill is being used, and which enemy used it.

Many games include a slight delay in the enemy's animation when the skill name is displayed. I remember at least FFVI doing this (and I seem to remember it being common in the series).

**Comment by Bertram25** [comment]
> Many games include a slight delay in the enemy's animation when the skill name is displayed.

I guess you mean that in FFVI, the enemy is slightly flashing before triggering its attack animation, right?

I agree the visual part of special skill presentation is an on-going improvement that needs more tuning. What have you got in mind when speaking of a "slight delay" here when transposed to VT?

**Comment by Suitecake** [comment]
A slight flash would be even better!

The slight delay I'm referring to would be extending the attack startup time, before the enemy lurches forward (indicating the attack itself).

So, if an enemy's normal attack animation is that the sprite stands still for 0.5 seconds, then lurches forward and back for 0.25 seconds, then a special attack animation would have the sprite standing still for 1.25 seconds, then lurching forward and back for 0.25 seconds. A slight extension of the initial time that the enemy sprite is standing still.

I really like the idea of the enemy slightly flashing before triggering the attack animation, and think that would be a great way of differentiating. I think that, even including that though, we'll need to adjust the timing of the skill callout (since at the moment it seems to extend well past the end of the special attack and into the next actor's attack, which means they bleed together if the next enemy uses the same special attack)

**Comment by Bertram25** [comment]
Ok, then if I get it, the main problem is that the callout is displayed past the attack time.
This can be tweaked here, btw:
https://github.com/Bertram25/ValyriaTear/blob/master/src/common/message_window.cpp#L67
https://github.com/Bertram25/ValyriaTear/blob/master/src/engine/indicator_supervisor.cpp#L474
https://github.com/Bertram25/ValyriaTear/blob/master/src/modes/battle/battle_actors.cpp#L1127

We'd need to add parameter in the indicator supervisor to set the desired time, or reduce the default time in the short notice class here:
https://github.com/Bertram25/ValyriaTear/blob/master/src/common/message_window.h#L81

Mind trying a few display time values and tell me?

As for the flash, we could first make the sprite change using its grayscaled version. I'd make it flash two times so that it is visually noticed, as seen in this video for instance: :)
https://www.youtube.com/watch?v=kGksl-_Mg4c

**Comment by Suitecake** [comment]
Yes, that's the issue; the callout is being displayed significantly past the attack time. I'll experiment with this a bit (thanks for the pointers!)

That flash would work great.
