### ISSUE TITLE
Some features are not documented/not obvious to the player

### ISSUE THREAD

**Issue by ghost** [ValyriaTear/ValyriaTear#516]
I'm mostly thinking about the choice of the body part to hit there, but there might be others.

So, some attacks allow to choose a body part to hit, and the consequences of this choice should be explained somewhere. If it has no consequences yet it should be explained too.

**Comment by Bertram25** [comment]
> So, some attacks allow to choose a body part to hit, and the consequences of this choice should be explained somewhere. If it has no consequences yet it should be explained too.

Actually, you have a small explanation about it, when on the body location selection, and pressing the menu key. But there are hidden game features not yet well reprensented.
As there are more to come (formation, skill tree), I'll be on that after adding everything.

Could you try the Menu key 'S' and tell me what else would be missing in your own opinion, if anything?

**Comment by akien-mga** [comment]
Maybe there could be hints about such features like getting more info by pressing the menu key on battle actions? Like a small tip window showing up during the first battle to explain the various interface elements are they become relevant.

**Comment by Bertram25** [comment]
> Maybe there could be hints about such features like getting more info by pressing the menu key on battle actions? Like a small tip window showing up during the first battle to explain the various interface elements are they become relevant.

True. I would even make it visible in all battles at the right moment. Thanks for the hint.
I thus propose to add an action icon + text when currently showing the body parts of an enemy. I still have to think about how to precisely do it, but that's the idea.

I also have to rethink the first battles in a more interesting way, I guess. Like tracking the first time certain interesting actions happen and show proper tips.

**Comment by libregametester** [comment]
Ok sorry, I didn't know about the 'S' key.

Nothing to add, except that I never remember which character property correspond to which icon and what they do.

It's explained in the dialogs but I think there should be _at least_ a "documentation" item in the main menu summarising the basics of the game.

Among other things that have confused me there were the appearance of the character portraits sometimes in the main adventure screen, and the loss of HP in the adventure screen (it took me a while to figure out I had been poisoned by a poison cloud).

--

**Comment by Bertram25** [comment]
> It's explained in the dialogs but I think there should be _at least_ a "documentation" item in the main menu summarising the basics of the game.

It would be cool indeed, but uneasy as long as all the game features are not there. I did started a static html documentation here, in case you need some, though. See: https://github.com/ValyriaTear/ValyriaTear/blob/master/doc/manual/index.htm
(You need to download the source first, though).
My actual goal is update this documentation and use it as a base to create the in-game documentation content afterwards.

> Among other things that have confused me there were the appearance of the character portraits sometimes in the main adventure screen, and the loss of HP in the adventure screen (it took me a while to figure out I had been poisoned by a poison cloud).

I can understand that. I guess the icon are not that much helping? What quick-tip would lacking to make you understand the portrait / Icons meaning in your opinion?

**Comment by akien-mga** [comment]
Based on this feedback I think @libregametester has not much experience with classical JRPGs like those of the Super Nintendo that ValyriaTear is heavily inspired from.

That's great feedback as we can now ask ourselves the question: which JRPG mechanics are not obvious to players who having played JRPGs as kids, and how to make them easier to understand without annoying experienced users (i.e. the mechanics should not necessarily be simplified, but just made easier to understand).

Contextual tooltips are a good way to do so IMO. But we need to define a list of concepts that need to be explained. BTW some classical JRPGs (at least the Final Fantasy's of the PSX) used to have in-game characters to explain the mechanics (which could quickly end up being too verbose, but that's another way to do it - with today's technology I think we can go easily with contextual tooltips instead though).

**Comment by libregametester** [comment]
On Thu, Jan 14, 2016 at 08:03:23AM -0800, Yohann Ferreira wrote:
> It would be cool indeed, but uneasy as long as all the game features are not there. I did started a static html documentation here, in case you need some, though. See: https://github.com/ValyriaTear/ValyriaTear/blob/master/doc/manual/index.htm

This is good. I would have saved time if I had read this when I've started playing the game.

I've juste read the "Battles" part. What happens when one of your characters die but you win the battle ?

> > Among other things that have confused me there were the appearance of the character portraits sometimes in the main adventure screen, and the loss of HP in the adventure screen (it took me a while to figure out I had been poisoned by a poison cloud).
> 
> I can understand that. I guess the icon are not that much helping? What quick-tip would lacking to make you understand the portrait / Icons meaning in your opinion? 

I guess the icons could be a bit better overall. If you show the Fortitude and Protection icons to a newcomer and ask him which one is the natural armor and which one is the magical armor, he won't be able to tell. Same thing if you show him the agility and the evade icon. And you can't really guess from the name either ("Vigor", "Fortitude", "Protection" and "Agility" are not really self-explainatory).

I'm not an expert in graphical design but I guess I would change the Vigor icon to something that looks more like a magick want and less like a torch/cigarette, perhaps with some swirls, or something that evocates a magical attack like a lightbeam. I would give the natural armor an icon that looks like a realistic shield (metal or wooden, sober colors, no colored halo), and give a shield with flashy colors to the magical armor. Or perhaps they could just be shields with the Strenght sword and the Vigor wand in front of them. I don't know how to improve the Agility icon but the Evade icon should probably have a target symbol somewhere. The target should not be on the silhouette but next to it (otherwise people would think it's an accuracy property. Btw, is there a property that increases character's accuracy ?)

The fact that there are base statistics one the one hand and combat statistics on the other hand is a bit confusing too, especially since the icons ar the same. Maybe they could represent the same things (sword, wand, etc), but differently, so we know the two stats are related but are not the same.

But more importantly, I think there should be a lot more textual information. Like the "Missed" message printed when a hit missed, I think that the "Stunned", "Poisoned", "Slowed", "Incapacitated", "Cured", "Healed", etc. messages could appear next to the corresponding icons. And a "+" or "-" sign could appear next to the points to specify whether they are gained or loss.

Similarly I would add the icons where they're not present, on the level advancement screen for example.

The choice of colors is a bit confusing too. There's red down arrow for loss and a green up arrow for gain, there's a yellow halo for loss and a light blue/cyan halo for gain, and HP are represented by a red cross and SP by a dark blue cross. I would unify the colors of the halos and the arrows, make the arrows slightly bigger, and change those red and blue crosses. At least unify the blue of the SP cross and the blue of the SP bar on the combat screen.

Also on the adventure screen there seem to be a bit of a delay between the printing/disappearance of the red cross and the black background/yellow halo/red arrow, which means that sometimes when you look on the bottom left corner you only see the red cross which is a bit confusing.

When you heal your party at a statue it would be nice to have a "+42" message with the corresponding portraits and icons, similarly to what happens when you lose health because of poison.

I would also add some more notifications, like a sound and maybe some graphical effects when you're poisoned by a cloud on the adventure screen (see the cheese attack in hedgewars to get an idea).

--

**Comment by libregametester** [comment]
On Thu, Jan 14, 2016 at 08:20:43AM -0800, Rémi Verschelde wrote:
> Based on this feedback I think @libregametester has not much experience with classical JRPGs like those of the Super Nintendo that ValyriaTear is heavily inspired from.

That's true, I'm just starting to test free RPGs now. So far I've looked at things like Ardentryst and Flare and I didn't have much trouble understanding the mechanics.

> Contextual tooltips are a good way to do so IMO. But we need to define a list of concepts that need to be explained. BTW some classical JRPGs (at least the Final Fantasy's of the PSX) used to have in-game characters to explain the mechanics (which could quickly end up being too verbose, but that's another way to do it - with today's technology I think we can go easily with contextual tooltips instead though).

In-game teachers are good since it's a fun way to learn the game, but they should be coupled with a documentation available all the time in case you don't remember something a character said (or you want it explained in a different way). Contextual tooltips are probably the best.

--

**Comment by Bertram25** [comment]
> In-game teachers are good since it's a fun way to learn the game, but they should be coupled with a documentation available all the time in case you don't remember something a character said (or you want it explained in a different way). Contextual tooltips are probably the best.

Duly noted. In-game teachers, contextual tooltips, and ultimately a game manual.

**Comment by Bertram25** [comment]
> I've juste read the "Battles" part. What happens when one of your characters die but you win the battle ?

Only survivors earn XP. Is there anything to add?

About the icons and the rest, I must say I agree overall and something should be done about this.
The stats may even need a rename to be more straight forward. For info, those icons were made based on the former Allacrost ones for speed purpose.
Now that this is done, it will be a clever thing to make it all more obvious, indeed.
I'll let this issue around and think about it some more before deciding the course of actions.

Thanks for the feed-back in any case. :)

**Comment by Bertram25** [comment]
Ah and better icons for base stats.

**Comment by Bertram25** [comment]
This will be done little by little. I may start with icons as it is the most important, but it will depends on my free time.

**Comment by Bertram25** [comment]
@libregametester @akien-mga This is all work in progress, but what do you already think?
(What's next is internal refactoring for the menu code and new icons for HP, SP, and stunned state.)
![screenshot_11](https://cloud.githubusercontent.com/assets/765917/13381432/6c94ef56-de5c-11e5-912c-6e2a1a698c99.png)

**Comment by akien-mga** [comment]
This looks very good! And wow, new characters! Episode 2 in the making? :-D

**Comment by Bertram25** [comment]
> And wow, new characters! Episode 2 in the making? :-D

Has been since a long time ago. ;) Nothing really new in term of data, but I'm getting close from being ready for the 1.1 release :D (Thanks also to @authenticate )

**Comment by libregametester** [comment]
This is definitely better. I suggest you work on the brightness of the shield icon to bring it out from the background a bit more, and work on the contrast of the magical defense icon so the central shield can be distinguished effortlessly. Apart from that the names and the icons are much more self-explanatory than the previous ones. Maybe I would still advocate for my "target next to the silhouette" idea for the evade icon.

--

**Comment by Bertram25** [comment]
Thanks for all the comments. :)
Ok, we are on it, the shields will probably go first following your comment. As for the evade one, Lilou has an idea about it as well, but that's for tomorrow or during the week. ;)

**Comment by Bertram25** [comment]
As this issue is getting crowded (which is bad to get things done), I'll try to split it now in bullet points, feel free to point out any missing thing:

- [ ] Add an action icon + text when currently showing the body parts of an enemy to hint about the help key (S)
- [x] If you show the Fortitude and Protection icons to a newcomer and ask him which one is the natural armor and which one is the magical armor, he won't be able to tell. Same thing if you show him the agility and the evade icon. And you can't really guess from the name either ("Vigor", "Fortitude", "Protection" and "Agility" are not really self-explanatory).
- [ ] Evade icon should probably have a target symbol somewhere. The target should not be on the silhouette but next to it (otherwise people would think it's an accuracy property) or similar.
- [ ] Like the "Missed" message printed when a hit missed, I think that the "Stunned", "Poisoned", "Slowed", "Incapacitated", "Cured", "Healed", etc. messages could appear next to the corresponding icons. -> Can be a game option: icon or text + icon.
- [ ] Similarly I would add the icons where they're not present, on the level advancement screen for example. -> level advancement is left, indeed.
- [ ] There's red down arrow for loss and a green up arrow for gain, there's a yellow halo for loss and a light blue/cyan halo for gain, and HP are represented by a red cross and SP by a dark blue cross. I would unify the colors of the halos and the arrows, make the arrows slightly bigger, -> I agree upon that part.
- [x] and change those red and blue crosses. At least unify the blue of the SP cross and the blue of the SP bar on the combat screen. -> icons were changed.
- [ ] Also on the adventure screen there seem to be a bit of a delay between the printing/disappearance of the red cross and the black background/yellow halo/red arrow, which means that sometimes when you look on the bottom left corner you only see the red cross which is a bit confusing. -> Reduce the delay while keep it slightly desync for coolness.
- [ ] I would also add some more notifications, like a sound and maybe some graphical effects when you're poisoned by a cloud on the adventure screen (see the cheese attack in hedgewars to get an idea). -> Good idea.
- [ ] In-game teachers. -> After quite some time thinking about this, I realized the Kalya house map was rather unused. I'll add something there about combat basics.
- [ ] Advanced in-game teachers. -> dialogue on first status effect. dialogue on first poison.
- [ ] I suggest you work on the brightness of the shield icon to bring it out from the background a bit more, and work on the contrast of the magical defense icon so the central shield can be distinguished effortlessly. -> yep.

Also, some bits I didn't answer:
> Btw, is there a property that increases character's accuracy ?)

Nope, that's why evade will remain low (while improving) for the entire game. Having a counter evade stats is uneasy to balance correctly anyway.

> The fact that there are base statistics one the one hand and combat statistics on the other hand is a bit confusing too, especially since the icons ar the same. Maybe they could represent the same things (sword, wand, etc), but differently, so we know the two stats are related but are not the same.

I do think the confusion was coming from the twisted base stats. I personally think it is a good thing to know natural stats and combat ones. It's some kind of standard, at least to me, and helps (me) know how equipment improve my character. I'd say let's give it some time.

> And a "+" or "-" sign could appear next to the points to specify whether they are gained or loss.

The color should indicate that. Is it not sufficient?

> Also on the adventure screen there seem to be a bit of a delay between the printing/disappearance of the red cross and the black background/yellow halo/red arrow, which means that sometimes when you look on the bottom left corner you only see the red cross which is a bit confusing.

ok, I'll reduce the delay, but I must say I find the slight desync cool to see.

> When you heal your party at a statue it would be nice to have a "+42" message with the corresponding portraits and icons, similarly to what happens when you lose health because of poison.

No, in that case, I think it doesn't make sense. The party is fully healed. You don't care how much they were healed. On the other side, it might be reassuring to see diseases go away when being healed with corresponding animations. Is that what you mean?
