### ISSUE TITLE
Use KWStyle or any code formatting help tool

### ISSUE THREAD

**Issue by ghost** [ValyriaTear/ValyriaTear#547]
Hi.

KWStyle can help to indicate rules that are not respected in source code. (It is packaged in at least Debian and Trisquel.)

I usually use this "KWStyle.xml":
```xml
<?xml version="1.0" encoding="utf-8"?>
<Description>
  <!-- Text -->
  <LineLength>90</LineLength> <!-- max -->
  <EmptyLines>2</EmptyLines> <!-- max -->
  <EndOfFileNewLine>true</EndOfFileNewLine>
  
  <!-- C/C++ -->
  <VariablePerLine>1</VariablePerLine> <!-- max -->
  <StatementPerLine>1</StatementPerLine> <!-- max -->
  <Struct>
    <regex>[a-z_]</regex>
  </Struct>
  <Functions>
    <regex>[a-z_]</regex>
    <length>150</length>
  </Functions> <!-- length = number of lines -->
  <Comments>
   <begin>/*</begin>
   <middle> * </middle>
   <end> */</end>
   <checkMissingComment>false</checkMissingComment>
  </Comments>
  
  <!-- C++ -->
  <DeclarationOrder>
    <public>0</public>
    <protected>1</protected>
    <private>2</private>
  </DeclarationOrder>
</Description>
```

But I have a lot of errors on your project with this rules. So it would be useful that you define rules for your project before a potential fix.

Then to use it, it is simple: `KWStyle -R -v -gcc -d src/`

Regards.

**Comment by Bertram25** [comment]
Interesting tools that actually slipped under my radar. I'll have to play with it, so give me a few days, so I'll make a few test but based on what I read in the example, I would just say:
- I don't care about the empty lines as long as there is not 10 lines between two functions or two code blocks. (I mean I don't really care if there are 2 empty lines instead of 1.)
- The max line length would rather be 100 characters. (We're in 2017, this even for vim users.) I you're coding under a 80 length terminal. It might be time to check the newest development tools out there, right?
- I'm not sure about what statement per line means but I'm pretty sure there could be exception there.
- The function/method comment style doesn't really matter here as long as it usable with Doxygen to me.

The rest can be discussed on a case basis.

Best,

**Comment by RyDroid** [comment]
- I do care, but use the limit you desire.
- I sometimes use a 1024*768 screen (an old computer in one of my parent house), that is one of the reason I care (it is not comfortable to read a line split "randomly" / not in an elegant way). The other one, that is most important, is to view multiple files at once (there is a way to do that at least in Emacs and Qt Creator) (again without "bad" splits due to the size of the buffer in the "Emacs language" or panel in Java Swing).
- `int a, b;` would be refused with `<VariablePerLine>1</VariablePerLine>`. With the same logic, `a=0; b=0;` would be refused with `<StatementPerLine>1</StatementPerLine>`.

**Comment by Bertram25** [comment]
- As for the empty line limit, let's put 3 and see what happens.
- I agree for the split screen feature as I use it daily. The thing is I was indeed thinking 1366x768 was the standard dev resolution nowadays and most of the code is fine with this. (Not that I think 100% of the code is fine ;]). Let's try 90 and see the errors.
- Let's try also 1 variable per line and one statement per line.

As for the regex of functions/methods and variables, I guess none or them will pass since the uppercased characters are missing. But it's not 100% clear when looking a the doc. I miss also the fact to exclude file types when parsing with KWStyle. But that's not a big issue.

**Comment by RyDroid** [comment]
- Done.
- Even with 120, there are a lot of reported too long lines. (https://github.com/ValyriaTear/ValyriaTear/pull/564 is just a very small piece)
- 188 errors for 1 variable per line and 1 statement per line!

**Comment by Bertram25** [comment]
Wow, indeed, adding this in the travis check will be very useful as medium term goal.

**Comment by Bertram25** [comment]
We should even make a CMake target to easily run this. E.g: make stylecheck or something similar. The target could exist only if the tool is detected on the system. I can have a go at this.

**Comment by RyDroid** [comment]
It would be great and not hard to do.

**Comment by Bertram25** [comment]
I'll finish the escape circle feature and tweak the monsters a bit in order to merge back new_game_balance asap. Then, I'll do it if you want.

**Comment by RyDroid** [comment]
Ok.

**Comment by Bertram25** [comment]
Actually done through .editorconfig. I consider it done but will always accept improvements there.
